# Generated by Django 3.0.8 on 2020-08-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=100)),
                ('real_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tz', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='ok', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('activity_period_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ActivityApp.ActivityMembers')),
            ],
        ),
        migrations.AddField(
            model_name='activitymembers',
            name='activity_user_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ActivityApp.ActivityStatus'),
        ),
    ]
