# Generated by Django 3.0.8 on 2020-08-08 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiods',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
