# Generated by Django 3.0.8 on 2020-08-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityApp', '0002_activityperiods_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiods',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activityperiods',
            name='start_time',
            field=models.DateField(),
        ),
    ]
