# Generated by Django 3.0.8 on 2020-08-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityApp', '0003_auto_20200808_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
