# Generated by Django 3.0.8 on 2020-08-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityApp', '0004_auto_20200808_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymembers',
            name='member_id',
        ),
    ]
